

import java.awt.CardLayout;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 許哲浩
 */
public class erp_frame extends JFrame {
    private CardLayout nowLayout;
    private Employee employee;
    private Attendance attendance;
    private PayRoll payRoll;
    private Achievement achievement;
    private Material material;
    
    public erp_frame() {
        initComponents();
        init();
        employee = new Employee();
        attendance = new Attendance();
        payRoll = new PayRoll();
        achievement = new Achievement();
        material = new Material();
        
        panel_dataInput.add("employee",employee);
        panel_dataInput.add("attendance", attendance);
        panel_dataInput.add("payRoll", payRoll);
        panel_dataInput.add("achievement", achievement);
        panel_dataInput.add("material", material);
//       setExtendedState(JFrame.MAXIMIZED_BOTH); 
        
    }
    private void init(){
        setResizable(false);
        setLocationRelativeTo(null);//置中
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("image/drink.png")));
        setTitle("公司名稱 : 休閒小棧 使用者名稱 : OOO 使用者代碼 : A123456789");
        
        DefaultTableCellRenderer tableAlign = (DefaultTableCellRenderer)table_firmData.getTableHeader().getDefaultRenderer(); //欄位置中
        tableAlign.setHorizontalAlignment(SwingConstants.CENTER);
        
        nowLayout = new CardLayout();       
        panel_dataInput.setLayout(nowLayout);

        
        
        

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_folder = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        treeFolder = new javax.swing.JTree();
        panel_dataInput = new javax.swing.JPanel();
        panel_dataShow = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_firmData = new javax.swing.JTable();
        text_search = new javax.swing.JTextField();
        label_search = new javax.swing.JLabel();
        JToolBar = new javax.swing.JToolBar();
        btnFirstData = new javax.swing.JButton();
        btnPreData = new javax.swing.JButton();
        btnNextData = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 1024));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_folder.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        treeFolder.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("ERP");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("人事資料庫");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("員工資料表");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("出缺勤表");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("員工考績表");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("薪資表");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("採購資料庫");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("進貨表");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("產品資料庫");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("產品資料表");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("庫存資料庫");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("原料庫存資料表");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("銷售資料庫");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("訂單資料表");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("訂單項目資料表");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("異常紀錄表");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("廠商資料表");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("會計資料庫");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("應負帳款管理表");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("客戶資料庫");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("客戶資料表");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("系統管理庫");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("帳號管理表");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeFolder.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        treeFolder.setRowHeight(30);
        treeFolder.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                treeFolderValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(treeFolder);

        javax.swing.GroupLayout panel_folderLayout = new javax.swing.GroupLayout(panel_folder);
        panel_folder.setLayout(panel_folderLayout);
        panel_folderLayout.setHorizontalGroup(
            panel_folderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
        );
        panel_folderLayout.setVerticalGroup(
            panel_folderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1018, Short.MAX_VALUE)
        );

        getContentPane().add(panel_folder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 1024));

        panel_dataInput.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_dataInput.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panel_dataInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 980, 470));

        panel_dataShow.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_dataShow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_firmData.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        table_firmData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "廠商名稱", "聯絡電話", "地址", "統編", "聯絡人", "付款條件", "備註"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(table_firmData);

        panel_dataShow.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 980, 460));
        panel_dataShow.add(text_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 150, 25));

        label_search.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        label_search.setLabelFor(text_search);
        label_search.setText("搜尋 : ");
        panel_dataShow.add(label_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        getContentPane().add(panel_dataShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, 980, 500));

        JToolBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JToolBar.setRollover(true);
        JToolBar.setAlignmentY(0.5F);
        JToolBar.setMaximumSize(new java.awt.Dimension(80, 50));
        JToolBar.setMinimumSize(new java.awt.Dimension(80, 50));
        JToolBar.setPreferredSize(new java.awt.Dimension(80, 50));

        btnFirstData.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        btnFirstData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/left-arrow-2.png"))); // NOI18N
        btnFirstData.setToolTipText("第一筆");
        btnFirstData.setPreferredSize(new java.awt.Dimension(80, 50));
        btnFirstData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFirstDataMouseClicked(evt);
            }
        });
        JToolBar.add(btnFirstData);

        btnPreData.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        btnPreData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/left-arrow.png"))); // NOI18N
        btnPreData.setToolTipText("上一筆");
        btnPreData.setPreferredSize(new java.awt.Dimension(80, 50));
        btnPreData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPreDataMouseClicked(evt);
            }
        });
        JToolBar.add(btnPreData);

        btnNextData.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        btnNextData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/right-arrow.png"))); // NOI18N
        btnNextData.setToolTipText("下一筆");
        btnNextData.setPreferredSize(new java.awt.Dimension(80, 50));
        btnNextData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextDataMouseClicked(evt);
            }
        });
        JToolBar.add(btnNextData);

        btnInsert.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        btnInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/insert.png"))); // NOI18N
        btnInsert.setToolTipText("新增資料");
        btnInsert.setPreferredSize(new java.awt.Dimension(80, 50));
        btnInsert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertMouseClicked(evt);
            }
        });
        JToolBar.add(btnInsert);

        btnModify.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        btnModify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit.png"))); // NOI18N
        btnModify.setToolTipText("修改資料");
        btnModify.setPreferredSize(new java.awt.Dimension(80, 50));
        btnModify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModifyMouseClicked(evt);
            }
        });
        JToolBar.add(btnModify);
        btnModify.getAccessibleContext().setAccessibleDescription("");

        btnClear.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/clear.png"))); // NOI18N
        btnClear.setToolTipText("清空輸入");
        btnClear.setPreferredSize(new java.awt.Dimension(80, 50));
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });
        JToolBar.add(btnClear);

        btnExport.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        btnExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/export.png"))); // NOI18N
        btnExport.setToolTipText("匯出");
        btnExport.setPreferredSize(new java.awt.Dimension(80, 50));
        btnExport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExportMouseClicked(evt);
            }
        });
        JToolBar.add(btnExport);

        btnDelete.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        btnDelete.setToolTipText("刪除資料");
        btnDelete.setPreferredSize(new java.awt.Dimension(80, 50));
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });
        JToolBar.add(btnDelete);

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Logout.png"))); // NOI18N
        btnLogout.setToolTipText("登出");
        btnLogout.setFocusable(false);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        JToolBar.add(btnLogout);

        getContentPane().add(JToolBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 980, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnFirstDataMouseClicked(java.awt.event.MouseEvent evt) {                                          
        System.out.println("FirstData");
    }                                         

    private void btnPreDataMouseClicked(java.awt.event.MouseEvent evt) {                                        
    	System.out.println("PreData");
    }                                       

    private void btnNextDataMouseClicked(java.awt.event.MouseEvent evt) {                                         
    	System.out.println("NextData");
    }                                        

    private void btnInsertMouseClicked(java.awt.event.MouseEvent evt) {                                       
    	System.out.println("Insert");
    }                                      

    private void btnModifyMouseClicked(java.awt.event.MouseEvent evt) {                                       
    	System.out.println("Modify");
    }                                      

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {                                      
    	System.out.println("Clear");
    }                                     

    private void btnExportMouseClicked(java.awt.event.MouseEvent evt) {                                       
    	System.out.println("Export");
    }                                      

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {                                       
    	System.out.println("Delete");
    }                                      

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {                                       
    	System.out.println("Logout");
    }            
    
    private void treeFolderValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_treeFolderValueChanged
        // TODO add your handling code here:
    	if(treeFolder.getSelectionPath().getLastPathComponent().toString()!=null){
    		String path = treeFolder.getSelectionPath().getLastPathComponent().toString();
    		if(path.equals("員工資料表")){
    			nowLayout.show(panel_dataInput, "employee");
    		}
    		else if (path.equals("出缺勤表")){
    			nowLayout.show(panel_dataInput, "attendance");
    		}
    		else if (path.equals("薪資表")){
    			nowLayout.show(panel_dataInput, "payRoll");
    		}
    		else if (path.equals("員工考績表")){
    			nowLayout.show(panel_dataInput, "achievement");
    		}
    		else if (path.equals("原料庫存資料表")){
    			nowLayout.show(panel_dataInput, "material");
    		}
            System.out.println(path);
    	}
        
        
        
        	//
       
        	
        
    }//GEN-LAST:event_treeFolderValueChanged
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(erp_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(erp_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(erp_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(erp_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new erp_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar JToolBar;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnFirstData;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnNextData;
    private javax.swing.JButton btnPreData;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel label_search;
    private javax.swing.JPanel panel_dataInput;
    private javax.swing.JPanel panel_dataShow;
    private javax.swing.JPanel panel_folder;
    private javax.swing.JTable table_firmData;
    private javax.swing.JTextField text_search;
    private javax.swing.JTree treeFolder;
    // End of variables declaration//GEN-END:variables
}
